### ISSUE TITLE
OverflowError

### ISSUE THREAD

**Issue by cs301cs301** [bishoph/sopare#20] opened 2018-04-17 11:56 UTC
Recording works, in mono, too. But there is an overflow error...

sopare 1.5.2
DEBUG:sopare.audio_factory:#### Default input device info #####
DEBUG:sopare.audio_factory:defaultSampleRate: 44100.0
DEBUG:sopare.audio_factory:defaultLowOutputLatency: 0.0087074829932
DEBUG:sopare.audio_factory:defaultLowInputLatency: 0.00580498866213
DEBUG:sopare.audio_factory:maxInputChannels: 2
DEBUG:sopare.audio_factory:structVersion: 2
DEBUG:sopare.audio_factory:hostApi: 0
DEBUG:sopare.audio_factory:index: 2
DEBUG:sopare.audio_factory:defaultHighOutputLatency: 0.0348299319728
INFO:sopare.worker:worker queue runner started
DEBUG:sopare.audio_factory:maxOutputChannels: 2
DEBUG:sopare.audio_factory:name: seeed-2mic-voicecard: – (hw:1,0)
DEBUG:sopare.audio_factory:defaultHighInputLatency: 0.0348299319728
INFO:sopare.buffering:buffering queue runner
DEBUG:sopare.recorder:SAMPLE_RATE: 16000
DEBUG:sopare.recorder:CHUNK: 512
INFO:sopare.recorder:start endless recording
INFO:sopare.processing:starting append mode
DEBUG:sopare.filter:New window!
Process buffering queue:
Traceback (most recent call last):
File „/usr/lib/python2.7/multiprocessing/process.py“, line 258, in _bootstrap
self.run()
File „/home/sopare/sopare/buffering.py“, line 43, in run
self.proc.check_silence(buf)
File „/home/sopare/sopare/processing.py“, line 74, in check_silence
self.prepare.prepare(buf, volume)
File „/home/sopare/sopare/prepare.py“, line 126, in prepare
self.tokenize(meta)
File „/home/sopare/sopare/prepare.py“, line 50, in tokenize
self.filter.filter(self.buffer, meta)
File „/home/sopare/sopare/filter.py“, line 126, in filter
chunked_norm = self.get_chunked_norm(nfft)
File „/home/sopare/sopare/filter.py“, line 62, in get_chunked_norm
i += int(progessive)
OverflowError: cannot convert float infinity to integer
INFO:sopare.recorder:Buffering not alive, stop recording
INFO:sopare.recorder:stop endless recording

same error if i read a .wav or .raw file.

**Comment by cs301cs301** [comment] 2018-04-17 14:46
here is output of ./sopare.py -l (after creating the dic!)

sopare 1.5.2
DEBUG:sopare.audio_factory:#### Default input device info #####
DEBUG:sopare.audio_factory:defaultSampleRate: 44100.0
DEBUG:sopare.audio_factory:defaultLowOutputLatency: 0.0087074829932
DEBUG:sopare.audio_factory:defaultLowInputLatency: 0.00580498866213
DEBUG:sopare.audio_factory:maxInputChannels: 2
DEBUG:sopare.audio_factory:structVersion: 2
INFO:sopare.worker:worker queue runner started
DEBUG:sopare.audio_factory:hostApi: 0
DEBUG:sopare.audio_factory:index: 2
DEBUG:sopare.audio_factory:defaultHighOutputLatency: 0.0348299319728
DEBUG:sopare.audio_factory:maxOutputChannels: 2
DEBUG:sopare.audio_factory:name: seeed-2mic-voicecard: - (hw:1,0)
DEBUG:sopare.audio_factory:defaultHighInputLatency: 0.0348299319728
INFO:sopare.buffering:buffering queue runner
DEBUG:sopare.recorder:SAMPLE_RATE: 16000
DEBUG:sopare.recorder:CHUNK: 512
INFO:sopare.recorder:start endless recording
INFO:sopare.processing:starting append mode
DEBUG:sopare.filter:New window!
DEBUG:sopare.worker:characteristic = 0 {'volume': 15244, 'peaks': [0, 5, 10, 14, 15, 65], 'df': 94, 'dfm': 3450866, 'fc': 606.8, 'zcr': 0, 'norm': [0.10935133984390594, 0.09668085496247761, 0.08568011987889064, 0.07981646849926544, 0.07579406698428724, 0.10141618831859614, 0.09112914012921405, 0.08574975463039335, 0.08355476306683064, 0.09170469326066764, 0.1024780876031649, 0.08853449417745059, 0.08909318594521487, 0.09425561899235321, 0.10996939732324511, 0.10584376309694611, 0.09209846996422301, 0.08113150133391538, 0.09695112424869685, 0.09530088457052928, 0.08448007831820287, 0.07304737030692092, 0.07148212652262659, 0.08630900894271505, 0.09186933768208519, 0.08062855740785001, 0.07309460656378408, 0.06881377925096513, 0.08232832261613177, 0.07371180649332493, 0.0658948679173174, 0.06089447312973458, 0.06737106731595582, 0.07429351700211172, 0.06406816912447658, 0.06389632792656252, 0.06515967021298304, 0.07524940010212779, 0.07339427082918283, 0.0706658022702824, 0.06295215011425874, 0.0669735516134708, 0.0792571233855015, 0.07169310492131836, 0.06800919796330102, 0.06463644536588845, 0.07525586851475194, 0.07795921172471956, 0.07797170031863038, 0.07187257945068373, 0.07458248003369185, 0.08738685360881107, 0.0775099921396784, 0.07768061037512941, 0.07588614443694289, 0.07867628711549098, 0.0833174791891067, 0.07441153539548515, 0.0754122778614868, 0.0793913230393574, 0.09133886205248834, 0.09256928373149591, 0.09065872006048002, 0.08778888946284344, 0.09329678951458543, 0.10415857824126121, 0.09526120962243795, 0.09085291243232842, 0.08629824673571677, 0.08952480256528116, 0.08454422151724605, 0.07296522963994471, 0.07378775277985157, 0.07416038928890803, 0.08366377737463214, 0.0760469056321619, 0.0731344455630373, 0.06393814750379602, 0.07273478375299412, 0.07371059888133571, 0.059535977415674526, 0.05916243328459496, 0.06107933266692879, 0.06469666218605913, 0.0688150453814011, 0.05905253122327085, 0.05029775041368453, 0.052112837057670496, 0.0450717709595119, 0.05387515519917973, 0.05008519473491902, 0.062091625064053094, 0.06726175528166688, 0.07367858987141565, 0.07205888749244181, 0.0640543785587704, 0.06916305755700254, 0.07865179031698487, 0.07476968899677269, 0.08075906792574464, 0.06967338900696268, 0.0796601448643674, 0.08643364420911445, 0.08509853566935595, 0.07501182623394967, 0.07296493459030325, 0.08021708921344327, 0.07212012377117118, 0.07489834416589601, 0.06564933599392368, 0.06929721722088146, 0.07233945518262634, 0.0627071244564514, 0.06691719735376953, 0.06393447872421285, 0.06958195410831546, 0.07180098435154171, 0.06208468955369211, 0.06756139629623625, 0.0685971494408684, 0.07285504220440277, 0.06490563845424517, 0.06729469635720292, 0.06385118066951623, 0.07305733211613397, 0.07544207283356448, 0.0612606240827792, 0.06784278161814858, 0.06059310315782893, 0.06950470543623172, 0.072004989525873, 0.06487444588059818, 0.06611020115130803, 0.06488421460948156, 0.06681770942932894, 0.059262885436620935, 0.06100664897111068, 0.05585155062408036, 0.0591857312274422, 0.05703775770733047, 0.05601785777351152, 0.05832108080154758, 0.056193189110274384, 0.061964883214534625, 0.05585671487243162, 0.062052956441008285, 0.06691403234952896, 0.0648887439973834, 0.07128853883419116, 0.06904319016964103, 0.05499659805258823, 0.05734047849989595, 0.06040199414237221, 0.05544659397068725, 0.05933247426051445, 0.06118421662658103, 0.06217903433052576, 0.06036954511798793, 0.05978885937791951, 0.060577011399243444, 0.055652580835671074, 0.05742427154231599, 0.059544674028445536, 0.05810455283550348, 0.055243416733493166, 0.052497772184369226, 0.059628449675705256, 0.06298490750663643, 0.060073122418440046, 0.0534539995455288, 0.0517934130240308, 0.05191583950953188, 0.05091296276443595, 0.052561474388443406, 0.049081531529754925, 0.05251169885381907, 0.061469249010661295, 0.0528700314418125, 0.043185529624302256, 0.05389352199533596, 0.0652851608334452, 0.06482267765824003, 0.06790610547161154, 0.06399140457852302, 0.063809932504493, 0.05956063178352729, 0.05238086276437654, 0.048102478446353875, 0.04869939632126553, 0.05730459616451783, 0.06311737744998434, 0.061999637119864205, 0.061592305846516426, 0.05855716473278354, 0.05437198789585113, 0.05038954536198432], 'token_peaks': [80195, 226052, 396619, 3275099, 6303196, 6252473]}
DEBUG:sopare.worker:meta = [{'adapting': 6252473, 'token_peaks': [80195, 226052, 396619, 3275099, 6303196, 6252473], 'pos': 6, 'volume': 15244, 'token': 'token', 'silence': 0}]
DEBUG:sopare.worker:characteristic = 1 {'volume': 480, 'peaks': [], 'df': 93, 'dfm': 1870823, 'fc': 738.9, 'zcr': 0, 'norm': [0.08606564873555479, 0.09516771321097833, 0.08140304666348507, 0.061607556598780304, 0.07802095097084956, 0.08760718174226936, 0.0999522463168722, 0.09539758298575483, 0.08698390897805566, 0.08921112677953047, 0.08893351620785771, 0.09273790649841479, 0.09268920832901921, 0.08763345108175805, 0.09335460378702866, 0.09422702538934381, 0.09027911940910373, 0.08964057574552586, 0.08087656336387118, 0.08146660704263274, 0.08154956246072344, 0.07200231251095135, 0.08326420917216218, 0.06879878986679659, 0.0719674580034382, 0.07678346973645218, 0.06785974147587115, 0.07523423940472758, 0.07333229108973807, 0.06584853743534494, 0.05957707581508678, 0.05796055287227111, 0.0646655712573591, 0.06872355085539768, 0.061203455723180505, 0.05489421393898489, 0.060385552929913516, 0.06661957325532418, 0.07060881892113871, 0.06972576256042258, 0.05659141485001103, 0.05493421040672042, 0.05699744435669297, 0.06873955298972245, 0.06989429173574377, 0.06593283376724857, 0.06360114376537396, 0.05901334383918718, 0.07337481579453642, 0.07759159579585581, 0.07190519469616866, 0.0713080793725239, 0.06739761885210273, 0.07935137320635377, 0.0810431194397582, 0.07490047896382056, 0.06358633617968668, 0.0632875574644275, 0.07289016664764429, 0.08065623032477057, 0.08679927426031073, 0.08038839585245486, 0.08524661340930306, 0.08696985612623176, 0.09182928325705433, 0.09275977234412665, 0.08582478922120144, 0.0744363572341148, 0.07503084616037113, 0.07480122904308568, 0.07732316698862246, 0.07414704590728995, 0.07052426574838602, 0.06361213239146898, 0.06587884572635848, 0.06871888688081991, 0.06791237862560548, 0.05441549054627381, 0.053799037652749356, 0.05077571580483172, 0.05835224271125754, 0.05504753791269186, 0.053245335605901375, 0.06103824359368549, 0.06158616215597023, 0.06040286450091152, 0.058780199832024885, 0.06067782786182755, 0.06036023444917742, 0.058789421476939205, 0.05356357974960429, 0.06109915461398133, 0.06503807973080433, 0.06250850805861025, 0.06843348551572992, 0.06900897849504949, 0.07457902941737209, 0.08086721722461035, 0.07972859737317542, 0.07003348147047767, 0.07735356155589028, 0.08388126401443244, 0.08828551708074435, 0.08588428597684826, 0.07841434933601737, 0.0730580165460848, 0.07089250395748779, 0.07069286655865219, 0.05479164265087127, 0.06178208406632161, 0.06019837071641971, 0.0550794105364048, 0.06399834219757458, 0.06447978284272467, 0.06255995620687048, 0.05919363048884588, 0.059117570509674484, 0.06476285981646077, 0.07099424836624466, 0.06764415540922004, 0.0661826944958283, 0.0658208695525259, 0.06546577722016517, 0.07133553574372735, 0.07104769099709192, 0.06725989461152027, 0.061980588361053884, 0.062017853608280604, 0.06559115762586323, 0.06386771296110831, 0.06115901530303998, 0.05569969421868461, 0.05735070182047009, 0.06306116915554971, 0.06855215196178074, 0.0680326981588849, 0.068389752913015, 0.0696588897822648, 0.06694034043753314, 0.06842500688086152, 0.07272512612132236, 0.07092346629631571, 0.06559992261127835, 0.06256315545557335, 0.06556041247033965, 0.0702379212107063, 0.07443722043424447, 0.06620888079645566, 0.06903985082489723, 0.07176499159513504, 0.06585850611399283, 0.06901579509860185, 0.0711388373669471, 0.07055135415433259, 0.06915032157439563, 0.06980271468218344, 0.07052262354443606, 0.0738967928152442, 0.07009897670775349, 0.08051682908809488, 0.07939393119405647, 0.07349628962787422, 0.06741346094087315, 0.06846299295852837, 0.06998166337673092, 0.07206125052008573, 0.06543917519910812, 0.05769672138679983, 0.058778621388948314, 0.05894466268630381, 0.05399401462259184, 0.06121874946796956, 0.05743330671537926, 0.06530142888157195, 0.055564372968557464, 0.06287073557561616, 0.063124047178209, 0.06082959497104617, 0.06445243593205417, 0.07264791123725141, 0.06892663596940718, 0.07219706120312423, 0.07444065934021736, 0.07537619063636446, 0.08003606489168205, 0.07920269381103949, 0.07324594131249555, 0.07327070472978227, 0.08165728635966679, 0.08074846880160509, 0.07647865820176575, 0.07425764251958661, 0.07920558888399491, 0.08437246607346006, 0.07969907259828687, 0.08081775710504921], 'token_peaks': [2909615, 1141340, 996053, 712142, 257490, 206771]}
DEBUG:sopare.worker:meta = [{'adapting': 206771, 'token_peaks': [2909615, 1141340, 996053, 712142, 257490, 206771], 'pos': 12, 'volume': 480, 'token': 'token', 'silence': 5}]
DEBUG:sopare.worker:characteristic = 2 {'volume': 2238, 'peaks': [], 'df': 967, 'dfm': 122657, 'fc': 823.2, 'zcr': 0, 'norm': [0.08817788414472431, 0.08402899857581154, 0.08532085426700779, 0.08773738672493708, 0.08139315856565756, 0.08813969372938783, 0.08673263715371918, 0.0828846026272259, 0.0781462632335137, 0.08326632351597364, 0.08379089555235131, 0.07907226990795511, 0.08169064870425093, 0.08159329329381532, 0.09022493072031733, 0.08293219704407431, 0.08507048739451199, 0.08136831432001139, 0.07694229125007382, 0.07618790749294442, 0.06990206022790262, 0.07820543157884076, 0.07775034970148458, 0.07714288813778007, 0.07966956245820486, 0.08049687276880317, 0.07643482597078508, 0.0713442643237501, 0.0664047188375913, 0.0661527717377594, 0.06592615246115019, 0.06262741176215093, 0.06297682755603827, 0.06507830690932827, 0.06855846894684593, 0.06610515810267911, 0.06551453327678146, 0.06560994388753193, 0.07469163444570188, 0.06446754854466659, 0.06730315514790376, 0.07022334093689417, 0.06979543994880867, 0.07189525757398013, 0.05858981244915912, 0.07121349685305792, 0.06950435875151058, 0.07071962490121636, 0.06764364927394843, 0.07435698491079903, 0.0763980891592094, 0.07421633771705409, 0.07206768081205647, 0.07166443300998449, 0.06797532565202152, 0.07059762870695158, 0.06930202672883812, 0.07437273521010733, 0.07641878810378894, 0.07730330361743473, 0.081837166608219, 0.08801207664020225, 0.0781270422254894, 0.08071028009992075, 0.07773526637622884, 0.07131954559680855, 0.07754074598271606, 0.0748827921732937, 0.07256496424172693, 0.0667484569388984, 0.06984830236988515, 0.06766378071254574, 0.0685548826572655, 0.05977706866470153, 0.06434595184843267, 0.06432498871128631, 0.05465558143918272, 0.052188880661481946, 0.05876031591777181, 0.05368566188372676, 0.05552288942690618, 0.05508125751272257, 0.049000690758264576, 0.06625768096644279, 0.06072904704584837, 0.05526790230598327, 0.056810026884992634, 0.05725214126724296, 0.054992356059344764, 0.05241160678424233, 0.05839571312316184, 0.05718548712195219, 0.05672972513816698, 0.05132225844912829, 0.05854095238634046, 0.05902677713975554, 0.058877991601477414, 0.05837971695546167, 0.06298942986144153, 0.06298862868756336, 0.06247527201924589, 0.06606859477298184, 0.07341680886062976, 0.08210351030226162, 0.07473484275122251, 0.08329756313941443, 0.08582333456949888, 0.08253542803570951, 0.06959397747676171, 0.05611620641465679, 0.06399203383015543, 0.062179736019584375, 0.0645001680114584, 0.06678531441747841, 0.06823705625515071, 0.05604174158935768, 0.05940042964302338, 0.059464697050986844, 0.05944101704061888, 0.0515358803360423, 0.06258204669639089, 0.05650114552962689, 0.05906788703274826, 0.05683388570517517, 0.06105347245214306, 0.05258136818947963, 0.059814046251473955, 0.058253130693028676, 0.05914640692880658, 0.062496877038970125, 0.06876854181425388, 0.0697267694434968, 0.0723656901769247, 0.0635410592552113, 0.06712668979452419, 0.058679078630146035, 0.05664617954250522, 0.07216246869539099, 0.06926634476090877, 0.07180222233543186, 0.06750122465493799, 0.06558283018084897, 0.06947531660381669, 0.07656753119867185, 0.07513653169438239, 0.08011581466572948, 0.07469775106556621, 0.08206735291241993, 0.07848409852326564, 0.08244638672093209, 0.08911368584678352, 0.08919282773635612, 0.08406591176554755, 0.09010769979213577, 0.09433827198282665, 0.08776861254914879, 0.08341572022481983, 0.07758616982990142, 0.07510385222092958, 0.07163451138434186, 0.07561617489848917, 0.07664408417278774, 0.0713650081590832, 0.06593618070468125, 0.07525694708609523, 0.06952167524126474, 0.05366770747903284, 0.06515982921143902, 0.06165046494937221, 0.05030739129926505, 0.0555507062153455, 0.059233234118656705, 0.05719451515925704, 0.056358864397786576, 0.06899213303626539, 0.06158714783226961, 0.06585475353444464, 0.06957700832156165, 0.06971582684116989, 0.07955862468994992, 0.08239641842394335, 0.07478495431347712, 0.07603051129989906, 0.08069617996844128, 0.07992939799859267, 0.07554993150728116, 0.06143444321517141, 0.08789654738453644, 0.08233580438667855, 0.09463831634705469, 0.0867630182108919, 0.08400168078913459, 0.08429721371380197, 0.08981620147787878, 0.08195806887089592, 0.09081983135103926], 'token_peaks': [210922, 820028, 1402191, 1472225, 1380124, 1139856]}
DEBUG:sopare.worker:meta = [{'adapting': 1139856, 'token_peaks': [210922, 820028, 1402191, 1472225, 1380124, 1139856], 'pos': 18, 'volume': 2238, 'token': 'token', 'silence': 11}]
DEBUG:sopare.worker:characteristic = 3 {'volume': 471, 'peaks': [0, 1, 2, 3, 4, 5], 'df': 30, 'dfm': 77190, 'fc': 433.4, 'zcr': 0, 'norm': [0.1067831205601941, 0.10088050440397058, 0.10540084002289828, 0.10502398747493036, 0.1044038947869239, 0.10134419128658231, 0.09535882054964347, 0.10015936359766259, 0.09319851747249148, 0.09376771784701275, 0.09276332305600576, 0.09261661799061174, 0.09057698085024073, 0.09118844113460212, 0.09380877069361551, 0.08480424550944125, 0.08417381191708638, 0.08045275316910326, 0.08503016530555338, 0.08314402964727531, 0.09026079992149702, 0.08325576348724509, 0.08115652309585362, 0.08005464657682396, 0.08173551312722344, 0.08267893473165541, 0.0839984579423088, 0.08044744374469623, 0.08228524896806116, 0.08585222314956265, 0.08396891180657681, 0.08209720534427435, 0.07840663946625276, 0.07684903291793492, 0.07753918499244428, 0.07363838888317872, 0.07723552244152926, 0.08229235501682669, 0.07478930177083085, 0.07808685722448427, 0.07805252083308452, 0.08105236482524063, 0.07716828234325113, 0.07601562841644077, 0.08302892399872613, 0.0798317515161189, 0.07523138630775689, 0.07267655203485408, 0.08028503821400258, 0.08258290820704457, 0.0889792079502277, 0.08489597173791052, 0.07979788766556464, 0.08561087655854646, 0.08758070908871614, 0.07884120478013498, 0.07331928263248794, 0.06521856155687486, 0.07168388013361243, 0.06216706175827947, 0.07003164968798967, 0.06955644306824298, 0.07379885458333675, 0.07965591515578553, 0.07182861082428318, 0.07993260612851848, 0.07077650961485704, 0.07937658380084732, 0.06021277885482645, 0.07225102036581184, 0.06746126813116363, 0.06741756692787508, 0.06809107038728043, 0.06887690919684594, 0.07480791331838148, 0.07065943287215808, 0.06713343994202702, 0.06891038669186056, 0.06717135244026917, 0.07475637496403549, 0.07061539328641586, 0.06091391018907567, 0.06956636420394445, 0.06710566408035705, 0.06471564663698419, 0.06802573504962993, 0.0703349596118979, 0.06554899413341408, 0.06714006086684192, 0.06533015176522335, 0.0655252148899534, 0.06220868186011011, 0.06497041304648679, 0.07114896342002308, 0.06321197221446485, 0.06884596164694753, 0.06535875548356791, 0.06932753198324042, 0.06265367560387144, 0.06752087962886172, 0.06598499680232812, 0.06677167717017508, 0.0659960552576701, 0.062463404477664596, 0.07057905934625547, 0.06714570307698565, 0.07151123509250236, 0.06447153579213094, 0.061576916527434765, 0.06867544065307533, 0.06717847130423557, 0.07190423411808046, 0.06623310069171966, 0.07091711672032011, 0.06169121473851753, 0.06975809210688451, 0.0610805645096375, 0.06020087894529435, 0.06736390322371216, 0.053900011827194484, 0.05591902440514243, 0.06603994393921, 0.0547236259111721, 0.05448993852963028, 0.05492385892341674, 0.06471837231277872, 0.06633860177533099, 0.0604669432491733, 0.06826525033673561, 0.06791709384123491, 0.05857497143079543, 0.06291096213472103, 0.06615666869427901, 0.06516475285476667, 0.06852529930792899, 0.06421784264242289, 0.06972806707892856, 0.06286401048959324, 0.06633479719374955, 0.06372217747527753, 0.05756477342852283, 0.06221811171233366, 0.06112786497519139, 0.06511812612211006, 0.06365884565409123, 0.062517724011826, 0.065516091921037, 0.06328968117706549, 0.06662303250864827, 0.05191521017806672, 0.06384793230208123, 0.05799506405596912, 0.05710352059805869, 0.058775062625242014, 0.0640933869775181, 0.05702511092668675, 0.06896452459852993, 0.06244828271110192, 0.05959106837813604, 0.05951735082473213, 0.055604118265992306, 0.06296768486391341, 0.05781960593453892, 0.06230475523656843, 0.05840112407256627, 0.06297266864006965, 0.05305391180306385, 0.06695984471345451, 0.06710451325282274, 0.05821296009795655, 0.0612547764545806, 0.05952700335886366, 0.06240842697575004, 0.0627137834714132, 0.06373763708811296, 0.05888727040681978, 0.062457710728517024, 0.06491989760676964, 0.057798015674647624, 0.06280075278151594, 0.06115741990113571, 0.056276233749603694, 0.057261448997607045, 0.06078406110568727, 0.06652329962820447, 0.05903094865597096, 0.06599321201037227, 0.06617702191366681, 0.05606212065784765, 0.0574842322736619, 0.06358009761495355, 0.05809222664277306, 0.06143587532613856, 0.05912714261100379, 0.06288100188886832, 0.05762110339981603], 'token_peaks': [822546, 873150, 674871, 157396, 47746, 228780]}
DEBUG:sopare.worker:meta = [{'adapting': 228780, 'token_peaks': [822546, 873150, 674871, 157396, 47746, 228780], 'pos': 24, 'volume': 471, 'token': 'token', 'silence': 17}]
DEBUG:sopare.worker:characteristic = 4 {'volume': 730, 'peaks': [], 'df': 35, 'dfm': 20714, 'fc': 409.9, 'zcr': 243, 'norm': [0.11217676915214499, 0.10909895912002901, 0.10474817623147757, 0.11199729865375056, 0.0994253442146802, 0.08995075926470963, 0.09936056093887262, 0.09829415713805757, 0.09451231319853272, 0.09480961785757916, 0.10151037601260976, 0.09027452540424218, 0.09303817964504224, 0.07843661477284436, 0.0830904421523633, 0.09451927476188358, 0.0922598043295255, 0.09766738873291342, 0.09145021582689596, 0.09173459454656462, 0.09657463894040712, 0.10387825187925388, 0.10390034662759505, 0.10853436715381637, 0.09126821902223448, 0.10143708459486653, 0.09165597452922541, 0.09695986036665755, 0.09374764434914089, 0.10030400639217919, 0.09862741158279774, 0.09550860029569926, 0.09583982475982787, 0.09042828597775888, 0.09683403393519098, 0.09603104600816226, 0.09533262922494853, 0.09368369341000088, 0.09314671354340512, 0.08643568176487242, 0.08913533019657076, 0.0729791559638988, 0.08254004466824857, 0.0747404032228374, 0.07394501707873664, 0.09245327512351782, 0.09329087147170445, 0.0827008808413815, 0.08702740139545423, 0.08128510054086123, 0.0815349169122655, 0.08937833777327506, 0.08344827013917082, 0.09212087122426468, 0.08320921259467856, 0.07575411826009858, 0.08515679716232018, 0.07643703809640319, 0.08775238182202731, 0.07375719644309288, 0.0794683697579934, 0.06993249511538614, 0.06415692362322964, 0.07718872743287498, 0.08353729685774687, 0.08173173221573489, 0.07649725126223787, 0.0786563076424465, 0.08581358976562266, 0.08244483262538463, 0.07677271142235148, 0.08161722289466536, 0.08109579688430016, 0.08278794978433705, 0.08495127794415633, 0.0796920897460722, 0.08088923977727196, 0.08133717537717754, 0.08775097722956855, 0.08587692133563615, 0.08918273764292164, 0.08345604572281248, 0.08610393567943744, 0.07526005621440064, 0.06948812944628198, 0.07555211516600865, 0.07296487856896586, 0.07338277914667574, 0.0762319180974018, 0.0721587298676463, 0.05923860366553863, 0.07414438776288747, 0.07455492217529741, 0.08063842578560292, 0.0785188826612363, 0.07426506298590518, 0.06776773629486915, 0.07689388636965606, 0.08309838717864929, 0.07293964447367741, 0.0781167261209698, 0.07923340038106554, 0.07883733207739102, 0.07177243613232483, 0.06614795188771729, 0.06887711190454511, 0.06003566281971215, 0.06917813878305322, 0.07149555756840272, 0.07068691289062018, 0.06807347045246183, 0.0667903729932355, 0.06859479437573603, 0.06484974411299241, 0.06953258536258462, 0.07326658379516363, 0.07788823099348209, 0.07604014353985118, 0.07548006225026985, 0.05805722348991186, 0.05436208383918194, 0.0734076877249822, 0.06793524894421617, 0.06546197972414043, 0.07442692493527718, 0.07889300805453921, 0.08089890318912264, 0.07558033618833908, 0.06485224593156338, 0.07345776183357478, 0.07334948840442548, 0.07830834687740845, 0.07803858898171963, 0.062312093730460934, 0.06351638912249442, 0.06723702653247951, 0.07302156641025596, 0.0695930314389512, 0.06745282529542315, 0.06963836919348115, 0.06735479815069124, 0.06503826270263378, 0.07150420553019687, 0.061585116014960355, 0.056122847805505346, 0.07129052094131774, 0.06603481691348141, 0.06095298165788056, 0.06492506709822506, 0.06021794837875462], 'token_peaks': [451071, 551299, 347193]}
DEBUG:sopare.worker:meta = [{'adapting': 347193, 'token_peaks': [451071, 551299, 347193], 'pos': 27, 'volume': 730, 'token': 'start analysis', 'zcr': 243, 'silence': 20, 'peaks': [80195, 226052, 396619, 3275099, 6303196, 6252473, 2909615, 1141340, 996053, 712142, 257490, 206771, 210922, 820028, 1402191, 1472225, 1380124, 1139856, 822546, 873150, 674871, 157396, 47746, 228780, 451071, 551299, 347193]}]
DEBUG:sopare.analyze:removing test from potential start position 1 bc MARGINAL_VALUE > 0.678895236778
DEBUG:sopare.analyze:removing test from potential start position 2 bc MARGINAL_VALUE > 0
DEBUG:sopare.analyze:removing test from potential start position 3 bc MARGINAL_VALUE > 0
DEBUG:sopare.analyze:removing test from potential start position 4 bc MARGINAL_VALUE > 0
Process worker for filtered data:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/sopare/sopare/worker.py", line 123, in run
    self.analyze.do_analysis(self.compare.get_results(), self.character, self.rawbuf)
  File "/home/sopare/sopare/analyze.py", line 55, in do_analysis
    matches = self.deep_search(framing, data)
  File "/home/sopare/sopare/analyze.py", line 91, in deep_search
    word_sim = self.deep_inspection(id, startpos, data)
  File "/home/sopare/sopare/analyze.py", line 137, in deep_inspection
    sim, sl, sr = self.token_sim(characteristic, dcharacteristic)
  File "/home/sopare/sopare/analyze.py", line 120, in token_sim
    sim_zcr = self.util.single_similarity(characteristic['zcr'], dcharacteristic['zcr']) * self.cfg.getfloatoption('compare', 'SIMILARITY_ZERO_CROSSING_RATE')
  File "/home/sopare/sopare/config.py", line 33, in getfloatoption
    return self.config.getfloat(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 362, in getfloat
    return self._get(section, float, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'similarity_zero_crossing_rate' in section: 'compare'
INFO:sopare.processing:stop append mode because of silence
INFO:sopare.buffering:stop buffering
INFO:sopare.processing:starting append mode
DEBUG:sopare.filter:New window!
INFO:sopare.processing:stop append mode because of silence
INFO:sopare.buffering:stop buffering
Traceback (most recent call last):
  File "./sopare.py", line 187, in <module>
    main(sys.argv[1:])
  File "./sopare.py", line 108, in main
    recorder.recorder(cfg)
  File "/home/sopare/sopare/recorder.py", line 44, in __init__
    self.recording()
  File "/home/sopare/sopare/recorder.py", line 88, in recording
    buf = self.stream.read(self.cfg.getintoption('stream', 'CHUNK'))
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

**Comment by bishoph** [comment] 2018-04-17 15:15
Ok, thx. The issue is fixed so I close the issue for now.

You need to make sure to add the option 

SIMILARITY_ZERO_CROSSING_RATE 

to the "Calculation basis" options and to your config file

in order to avoid the above "error" message. The option was introduced with one of the last commits.

**Closed by bishoph** 2018-04-17 15:15 UTC
Labels: bug
